### ISSUE TITLE
default colors don't overlay nicely rating graph

### ISSUE THREAD

**Issue by krofna** [cheran-senthil/TLE#1]
pick 5 colors which are actually visible on the graph

**Comment by cheran-senthil** [comment]
Close wrt https://github.com/cheran-senthil/TLE/commit/2a58b90c7279f6bcbfd87073461abc9f3845c725?

**Comment by krofna** [comment]
not really. it was a minor improvement tho

**Comment by krofna** [comment]
https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.set_prop_cycle.html
https://matplotlib.org/3.3.1/users/dflt_style_changes.html#colors-in-default-property-cycle
