### ISSUE TITLE
;vc sometimes recommends contests with solved problems

### ISSUE THREAD

**Issue by krofna** [cheran-senthil/TLE#116]
![image](https://user-images.githubusercontent.com/1102695/63390026-ea597300-c3ad-11e9-9552-0859e70ce9df.png)

**Comment by krofna** [comment]
problem: we go tru user submissions and discard contest id of submissions but instead we should check each problem name for match in set of solved problems.

**Comment by aneesh2312** [comment]
Is anyone working on this? If not, I would like to.

**Comment by krofna** [comment]
![image](https://user-images.githubusercontent.com/1102695/63649873-6dc6eb80-c743-11e9-88a7-48c76a9e2e58.png)
@aneesh2312 go for it

**Comment by meooow25** [comment]
@aneesh2312 this issue is now unblocked since we have proper problemset caching. Do you want to continue your work?

**Comment by aneesh2312** [comment]
Right now I am working on ;fullsolve (which is delayed because I am busy irl :|). But I will get to this once I am done with ;fullsolve. Or if someone else wants to, that's fine by me.

**Comment by krofna** [comment]
solved
