### ISSUE TITLE
;vc recommends contests that haven't started yet

### ISSUE THREAD

**Issue by aneesh2312** [cheran-senthil/TLE#123]
The VC picker sometimes recommends contests that have not started yet. There's no filtering of the contest list based on the phase the contest is in (at the time of raising the issue, latest contest is 1208, VC is recommending 1210). 

![Screen Shot 2019-08-25 at 8 30 50 PM](https://user-images.githubusercontent.com/14341543/63651868-3f630380-c777-11e9-8f20-780409597c09.png)

Results in 

![Screen Shot 2019-08-25 at 8 31 27 PM](https://user-images.githubusercontent.com/14341543/63651876-4f7ae300-c777-11e9-855d-80ae18c28b83.png)

**Comment by algmyr** [comment]
Closed by #127
