### ISSUE TITLE
;gitgud ;gotgud

### ISSUE THREAD

**Issue by krofna** [cheran-senthil/TLE#13]
- rename ;gitgud to ;gimmie
- new command ;gitgud will give a problem of desired relative difficulty, from -200 to +200
- give points based on relative difficulty: 1 2 3 4 5 (-200 -100 0 100 200)
- also give burles (berland currency) for betting
- allow a skip of unsolved after 12 hours
- ;gotgud reports completion
- overall leaderboard: tiebreaker is # of skips

**Comment by narutse** [comment]
I'll do the basics of these parts once meooow implements the compression stuff in there. I'll make it rely less on cache, esp. for the new gitgud version we have to fetch the submission history every time to make sure the problem really hasn't been solved. (i'll keep the cache for ;gimme in case the user does repeated calls.) I'll start doing it tmr/this weekend. Someone should design the database.

**Comment by narutse** [comment]
oh we also might have to deal with the same problem in div1 and div2 to avoid assigning a problem that's already been solved. maybe identify problems by name and something else since names are not unique? name and contestId close to each other?

**Comment by krofna** [comment]
implemented.
