### ISSUE TITLE
Show role changes for updateroles command

### ISSUE THREAD

**Issue by meooow25** [cheran-senthil/TLE#154]
It will be nice to show role changes for every user on `;updateroles`

**Comment by albertopoljak** [comment]
As in a form of embed? Like this but before it:
`await ctx.send(embed=discord_common.embed_success('Roles updated successfully'))`
?

What if the message is too long?

**Comment by algmyr** [comment]
Probably an embed, yes. Something simple like a list of

    name: old role -> new role

in a code block would do fine.

**Comment by meooow25** [comment]
Hello, welcome to the repo. This issue is sort-of on hold now, since ties in with #164 which we have thought of recently. I would recommend looking at any other issue marked as "good first issue" instead.
