### ISSUE TITLE
migrate ;gudgitters to ;handle pretty-like image

### ISSUE THREAD

**Issue by krofna** [cheran-senthil/TLE#160]
![image](https://user-images.githubusercontent.com/1102695/65832795-dbc57c00-e2c8-11e9-8a8a-bd43a220fbba.png)

**Comment by meooow25** [comment]
Misalignment is a known issue, #150.
Whether to switch to image is a different matter.

**Comment by krofna** [comment]
#150 is ;handle pretty doesn't support Japanese :thinking:

**Comment by meooow25** [comment]
My mistake, I meant #136.

**Comment by krofna** [comment]
Implemented long ago.
