### ISSUE TITLE
option to show only official participants in ranklist

### ISSUE THREAD

**Issue by krofna** [cheran-senthil/TLE#244]
Note that this shouldn't be default, since people primarily use ;ranklist for virtual contests.
So I suggest -virtual (as opposed to +virtual) option.

![image](https://user-images.githubusercontent.com/1102695/70863604-2363b780-1f4a-11ea-93ae-84a2983f670d.png)

**Comment by algmyr** [comment]
Likely solved by #509, open again if not.
