### ISSUE TITLE
plot rating distribution

### ISSUE THREAD

**Issue by krofna** [cheran-senthil/TLE#3]

**Comment by krofna** [comment]
CAREFUL: API may be requested at most 5 times in one second. If you send more requests, you will receive a response with "FAILED" status and "Call limit exceeded" comment.

**Comment by cheran-senthil** [comment]
But why?

**Comment by krofna** [comment]
cuz we ratist, remember? ;showhandles should do it on top of table

**Comment by krofna** [comment]
Maybe even make a histogram of server ratings

**Comment by krofna** [comment]
also highlight invoker's bar with different color

**Comment by krofna** [comment]
also color bars with cf rating colors

**Comment by aryamanarora** [comment]
isn't this easy smh

**Comment by krofna** [comment]
k arrayman, you do it

**Comment by aryamanarora** [comment]
smh ok

**Comment by krofna** [comment]
implemented
