### ISSUE TITLE
Contest reminder

### ISSUE THREAD

**Issue by Abdulrahmannaser** [cheran-senthil/TLE#309]
contest reminder doesn't work even for admins

**Comment by krofna** [comment]
Can you be more precise?

**Comment by Abdulrahmannaser** [comment]
I use the bot on my server and `;remind here` doesn't set the reminder

**Comment by krofna** [comment]
You need to specify a mentionable role which will be notified. Read `;help remind here`. This is a bug tracker not a support forum so I'm closing this.
