### ISSUE TITLE
Raise handle not found error in ;duel challenge

### ISSUE THREAD

**Issue by aryanc403** [cheran-senthil/TLE#356]
`;duel challenge @Git the lines`
Debug logs -
`tle.util.codeforces_common.HandleNotRegisteredError: Codeforces handle for @Git the lines not found in database`
It doesn't return any error in the server. It looks like TLE didn't respond to the command.

We never raise `handle not found error` in https://github.com/cheran-senthil/TLE/blob/master/tle/cogs/duel.py#L108 . We should do this.

**Comment by krofna** [comment]
send_error_if(cf_common.ResolveHandleError) in duel.py
