### ISSUE TITLE
Deprecate "Admin"/"Moderator" roles in favour of "TLE Admin"/"TLE Moderator" roles.

### ISSUE THREAD

**Issue by aryanc403** [cheran-senthil/TLE#372]
The bot has a lot of Admin/Moderator only commands.
`@commands.has_role('Admin')`
`@commands.has_any_role('Admin', 'Moderator')`
It's not necessary that the one who has the "Admin/Moderator" role in the server will be the "Admin/Moderator" of the bot.
A long term plan is to use "TLE Admin" and "TLE Moderator" roles.

Plans to execute this -
For backward compatibility first deprecate "Admin/Moderator" roles possibly by overloading these functions and give a warning if someone runs these commands with an "Admin/Moderator" role but without "TLE Admin"/"TLE Moderator" role a mention that you won't be able to run these commands in future.

After few months just remove these all together and allow "TLE Admin"/"TLE Moderator" to run these commands instead of "Admin"/"Moderator" roles.

**Comment by Nathan13888** [comment]
@aryanc403 Why don't you submit a pull request with those changes instead?

**Comment by aryanc403** [comment]
Seniors don't code.

**Comment by aryanc403** [comment]
![Meme](https://media.discordapp.net/attachments/560991726505033748/683700019127517219/unknown.png?width=1135&height=635)

**Comment by cheran-senthil** [comment]
I don't like this.

**Comment by Nathan13888** [comment]
That's quite a terrible excuse...

**Comment by algmyr** [comment]
We could default to Admin/Moderator and make it customizable through env vars. Flexibility if needed, but no change for current users.

**Comment by algmyr** [comment]
What would be needed:
* Add two variables to constants.py, `TLE_ADMIN = 'Admin'` and `TLE_MODERATOR = 'Moderator'`.
* In the bot init check for environment variables with the same names. If they exist, overwrite the default values.
