### ISSUE TITLE
;plot country broken for single parameter

### ISSUE THREAD

**Issue by krofna** [cheran-senthil/TLE#392]
![image](https://user-images.githubusercontent.com/1102695/95218100-3a82d700-07f4-11eb-8238-d9a4e41d8b79.png)

**Comment by PotatoHashing** [comment]
This may be fixed in an updated Seaborn version. https://github.com/mwaskom/seaborn/issues/2013

I haven't verified.

**Comment by PotatoHashing** [comment]
![image](https://user-images.githubusercontent.com/8847876/97079875-c5cadd80-15e6-11eb-9776-2c3b30078855.png)

Verified it works in seaborn 0.10.1.

**Comment by algmyr** [comment]
Cool. Thanks for investigating! I guess there is nothing for us to do then.
