### ISSUE TITLE
Move to discord.py=1.5.0

### ISSUE THREAD

**Issue by AntohiRobert** [cheran-senthil/TLE#393]
We should rewrite as fast as possible for discord.py=1.5.0 since this version breaks the mod(server members not recognized) and the v6 (current) gateway closure is "imminent". See: https://discordpy.readthedocs.io/en/latest/intents.html
Error encountered with version 1.5.0: ;handle list(and others) do not work, lists only members that are in voice channel. Probably can't read server(guild) members.

**Comment by algmyr** [comment]
Closed by #409.
