### ISSUE TITLE
Make self registration possible, if config (env var) is set

### ISSUE THREAD

**Issue by algmyr** [cheran-senthil/TLE#396]
Some servers modify the code themselves to allow self registration. We should consider making that possible in our bot with a config setting. As always, default to the behavior we currently have but make it overridable using an env var.

**Comment by PotatoHashing** [comment]
Is there more discussion needed or can I take this bug?

**Comment by algmyr** [comment]
I guess it's not obvious exactly how we want to allow for it. Possibly a separate command that is flag protected? Feel free to work on it and implement something that makes sense to you. :)

For the env variable, add a constant in constants.py and override it in the main method if env variable is set.

(Also documenting env variables somewhere would be great)

**Comment by algmyr** [comment]
Fixed by #402.
