### ISSUE TITLE
Add CSES ranklist depending on solved problems for registered users

### ISSUE THREAD

**Issue by Denjell** [cheran-senthil/TLE#405]
The current CSES leaderboard only supports fastest and shortest ranklists which are not very interesting to the average CSES user. I think a ranklist based on solved problems for server members that registered their user-id would add a bit of competitive note to it and would encourage more people to get involved in solving CSES problems.
Actually i have a list of people i know that do CSES and check it from time to time but it would be really nice to have this included in the Bot.

**Comment by PotatoHashing** [comment]
Would we have to register CSES handles?

**Comment by Denjell** [comment]
I don't know what would be the best way to implement it. 
Users and their solved counts are accessible via leaderboard (https://cses.fi/problemset/stats/) or a page per user (https://cses.fi/user/16493). I can imagine that polling the CSES leaderboard is traffic and computing heavy. 
My idea would be that users can set their user id and then a leaderboard with just these ideas will be generated. Idk if it is needed that users register and verify their id. Maybe let users or mods set it for the users that are interested in appearing in the leaderboard. Currently i handle it with a personal friends list but it is incomplete and only visible for me.

**Comment by algmyr** [comment]
@ollpu Do you have any suggestions? I remember you talking about making an api a while back, not sure of anything happened on that front though.

**Comment by ollpu** [comment]
> I remember you talking about making an api a while back

Yeah, the project is a little stalled right now but it's in the works. We hope we can accomodate some wishes for aggregate statistics like this, and these can be implemented among the first features in the API.
