### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by iampjeetsingh** [cheran-senthil/TLE#468]
I have implemented the following features in [my fork](https://github.com/iampjeetsingh/TLE) and would like to get them merged into the main branch.

- Codechef rating based roles
- CodeChef / AtCoder / Google Kickstart support in `;plot rating/performance` , `;ranklist` and `;handle pretty` using clist.by
- CodeChef and AtCoder support in `;handle identify` command
- Google Kickstart and LeetCode support in `;handle set` command (Todo: add them into identify)
- Ability to create HandleLists of users who are not present in the server.
- Updated `;remind` to [aryanc403/remind](https://github.com/aryanc403/remind)
- Ban feature (to restrict bot from responding to certain users)
- Commands to create roles for codeforces and codechef

How to proceed?

To try these features join [Priyansh31dec Server](https://discord.gg/AsBVjYScJH)

**Comment by cheran-senthil** [comment]
Make partial PRs for each feature, and we can take a look. Some of these sound like good ideas and might get merged
