### ISSUE TITLE
codeforces user stock trading

### ISSUE THREAD

**Issue by krofna** [cheran-senthil/TLE#5]

**Comment by cheran-senthil** [comment]
Is this still a thing? Betting what exactly?

**Comment by krofna** [comment]
betting on performance of a contestant. it's easy to do and will very much be a thing in few weeks

**Comment by krofna** [comment]
adopt nimbus idea of trading stocks of cf users

**Comment by krofna** [comment]
wontfix. maybe consider existing solutions in other bots.
