### ISSUE TITLE
How can i add this to my discord server 

### ISSUE THREAD

**Issue by ayush-india** [cheran-senthil/TLE#515]
i dont want it to run locally on my pc so how can iadd it

**Comment by ayush-india** [comment]
@krofna @orendon @Chillee @aryamanarora please sir add this message that you can use replit for free hosting 

this will help begginers like me for some free hosting. Thank you

**Comment by algmyr** [comment]
We have pretty generic instructions for how to run the thing, figuring out where to host it is up to you as the user.

We are not in the business of trying to push some specific service, and in particular we don't want to try to guarantee things will keep working on some platform, especially free tiers and/or hacky setups where you run into issues with resource limits, persistence, or whatever else.

If you can make it work, good for you, but we're not planning to support you outside fixing stuff that would be broken on a normal machine.

**Comment by ayush-india** [comment]
@algmyr true man, but you can can just list some possible hosting places, 

i just want the other people not to waste their time and effort. :smile:
