### ISSUE TITLE
fix broken rating plots

### ISSUE THREAD

**Issue by krofna** [cheran-senthil/TLE#67]
![](https://cdn.discordapp.com/attachments/561712928999473152/592409865985720356/plot.png)

**Comment by krofna** [comment]
@algmyr did we ever figure this out? i think i haven't seen it in very long time

**Comment by algmyr** [comment]
I haven't seen it either. I can't recall if there was a change that touched the formatting at some point that resolved this. Could also have been a bug that was fixed upstream. We can close this until we happen to see it again (if ever).
