### ISSUE TITLE
non-cancer contest reminder

### ISSUE THREAD

**Issue by krofna** [cheran-senthil/TLE#7]

**Comment by aryamanarora** [comment]
I wonder who has a cancer contest reminder :thinking:

**Comment by krofna** [comment]
top 10 anime mysteries

**Comment by krofna** [comment]
Make a ;subscribe command which will cause bot to DM the subscriber 1 hour and 10 minutes prior the contest

**Comment by meooow25** [comment]
Done, implemented in 485174b1e3f369645899649e1360798e212f857e and 090d1c2aee9b999364b7929b3ab1e5d7da429a44
